### ISSUE TITLE
Unhandled exception while deleting

### ISSUE THREAD

**Issue by sadrasabouri** [sepandhaghighi/samila#110]
#### Description
This bug occurs when you're using atplotlib pyplot figure to see your art when you close the matplotlib figure.
#### Steps/Code to Reproduce
```
import matplotlib.pyplot as plt
from samila import GenerativeImage, Projection

g = GenerativeImage()
g.generate()
g.plot()
plt.show()
```
After running this code when you close the matplotlib figure, you'll see:

#### Expected Behavior
Nothing

#### Actual Behavior
```
Exception ignored in: <function GenerativeImage.__del__ at 0x7f258fede1f0>
Traceback (most recent call last):
  File "/home/user/Programing/Git/samila/samila/genimage.py", line 200, in __del__
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 2762, in clf
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 925, in delaxes
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 292, in process
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 96, in _exception_printer
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 287, in process
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 2894, in <lambda>
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2799, in notify_axes_change
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3302, in update
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 797, in set_history_buttons
RuntimeError: wrapped C/C++ object of type QAction has been deleted
```
#### Operating System
Ubuntu 20.04

#### Python Version
`3.8`

#### Matlplotlib Version
`3.5.1`

#### Samila Version (Use : `samila.__version__`)
`0.5`

**Comment by sepandhaghighi** [comment]
It's a weird issue and this doesn't always happen!!
I will try to fix it after #109
